version: '3'
services:
  ntopng:
    image: ilm4zz4/ntopng:ntopng_3.8.1_ndpi_3.0_OpenSSL_1_0_2u 
    command: "entrypoint.sh"
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./data:/workspace/data
    restart: unless-stopped

